Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -110,7 +110,19 @@ jobs:
           echo "path: $(pwd)"
           ls -l /home/runner/work/MATE_BackEnd/MATE_BackEnd/docker-compose.yml
 
-     # docker-compose.yml 파일 서버로 전달
+          
+      - name: Clean up existing docker-compose.yml
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            if [ -d "/home/ubuntu/docker-compose.yml" ]; then
+              echo "A directory named docker-compose.yml exists. Removing it..."
+              rm -rf /home/ubuntu/docker-compose.yml
+            fi
+
       - name: Send docker-compose.yml
         uses: appleboy/scp-action@master
         with:
@@ -118,9 +130,9 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           source: /home/runner/work/MATE_BackEnd/MATE_BackEnd/docker-compose.yml
-          target: /home/ubuntu/docker-compose.yml
+          target: /home/ubuntu/
 
-      # 서버에서 Docker Compose 명령어 실행
+     # 서버에서 Docker Compose 명령어 실행
       - name: Run Docker Compose
         uses: appleboy/ssh-action@master
         with:
@@ -129,7 +141,12 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd /home/ubuntu
-            sudo docker compose down --remove-orphans
-            sudo docker compose pull
-            sudo docker compose up -d
-
+            if [ -f "docker-compose.yml" ]; then
+              echo "docker-compose.yml found. Proceeding with Docker Compose commands..."
+              sudo docker compose down --remove-orphans
+              sudo docker compose pull
+              sudo docker compose up -d
+            else
+              echo "docker-compose.yml not found. Exiting."
+              exit 1
+            fi
